### ISSUE TITLE
contract verifications

### ISSUE THREAD

**Issue by LiorRabin** [argentlabs/argent-contracts#116]
Hi,
We are using `WalletFactory.createCounterfactualWallet` method to create wallets on Mainnet.
How do we verify the contracts for the wallets?
The `WalletFactory` itself we were able to verify - https://etherscan.io/address/0x2FE1F9bBC9CE8Ea4E00F89FC1a8936DE6934b63D#code
This is the `Wallet` we're trying to verify - https://etherscan.io/address/0x7540bc4c7eab8507ab67c5c070e88e560793e746
Thanks

**Comment by elenadimitrova** [comment]
The Wallet as well seems verified. Can you confirm?

**Comment by LiorRabin** [comment]
Yes, we managed to verify eventually. Closing the issue, thank you.
