### ISSUE TITLE
Checksum Addresses 

### ISSUE THREAD

**Issue by sambacha** [argentlabs/argent-contracts#127]
# Checksum Addresses when scanning through QR Code 

**Application**: Android 
Unsure if this applies to iOS, as I know the two apps do not have feature parity, I also do not know if that is still true.

**Issue**: Argent does not return a checksum (i.e. validation and encoding) of addresses.

### **Example** 

`0x5aAeb6053F3E94C9b9A09f33669435E7Ef1BeAed` = `true`

`0x5AAEB6053f3e94c9b9a09f33669435e7ef1beaed` = `false`

**Severity**: low-risk, no funds at risk

**Informative**: 
[checksum addresses through this simple interface](https://ethsum.netlify.app/)

**Comment by elenadimitrova** [comment]
Thanks for reporting. We've logged it with the Android app team as this is application only issue rather than contracts.
