### ISSUE TITLE
USERNAME.argent.xyz

### ISSUE THREAD

**Issue by TimBoudewijns** [argentlabs/argent-contracts#171]
When opening the personal wallet website on mobile in Chrome shows everything mirrored. 

![Screenshot_2020-11-06-16-11-58-145_com android chrome](https://user-images.githubusercontent.com/51700403/98382213-33492600-204b-11eb-909a-8d54031a4f5b.jpg)

**Comment by elenadimitrova** [comment]
Thank you for the report. This was due to a chromium bug which is now fixed.
