### ISSUE TITLE
High GAS fees problem

### ISSUE THREAD

**Issue by riteshkakkad** [argentlabs/argent-contracts#183]
## Issue description
Looks interesting, unable to get good multisign wallet option like argent, only problem is high gas fees and to reduce GAS fees (near to zero ) would you consider to Add ETH compatible DPOS chain (XinFin Network) support? 

here is the brief.
url: https://xinfin.network/
RPC: https://rpc.xinfin.network/
Addresses have prefix "xdc" instead of "0x"
no change in tx hashes
Remix : https://remix.xinfin.network/
Support solidity and smart contracts
other api: https://mycontract.co/

Happy to talk commercials as well as ready to support with large XinFin Community members support to grow adoption with argent team.

**Comment by elenadimitrova** [comment]
Thanks for the suggestion, however we are already working on a chosen Layer 2 solution as well as a new more gas-efficient version of the Layer 1 wallet.
