### ISSUE TITLE
Android and iOS application source code

### ISSUE THREAD

**Issue by shalzz** [argentlabs/argent-contracts#278]
## Issue description
I didn't manage to find the source code for the android and iOS applications.

While its appreciable to have the smart contracts used by argent open source, its equally important to open source the client applications as key generation and storage is still handled by the argent applications among many other reasons (security, reproducibility, privacy concerns, etc)

**Comment by sambacha** [comment]
Argent publishes an iOS Application, there is obligated to follow the legal parameters set forth by Apple in its ** Minimum Terms of Developer’s End-User License Agreement**

[ read the minterms here: https://www.apple.com/legal/internet-services/itunes/dev/minterms/](https://www.apple.com/legal/internet-services/itunes/dev/minterms/)

As for the security model, [see the deployment address here](https://etherscan.io/address/0x46cf7ddb8bc751f666f691a4f96aa45e88d55d11#code) and the [multisig address here](https://etherscan.io/address/0xa5c603e1C27a96171487aea0649b01c56248d2e8#code)

If you would like to re-deploy Argent in a test environment to examine its reproducibility, checkout this repository here: https://github.com/Amxx/ArgentReplay by @Amxx - Its a test chain to show how Argent could redeploy the exact wallet addresses on different chains wit the same exact security guarantees.

**Comment by shalzz** [comment]
Well that doesn't answer how a private key is generated and stored by the application.
And if the private key is not also uploaded or inadvertently leaked to someone outside the device.

**Comment by delaaxe** [comment]
Our security model relies on the smart contracts.

You're protected even in case of compromised private key. While we do have some open source components, we haven't yet made a decision on open sourcing the full app. Note that on iOS this would not provide any additional garanty as you have no way to ensure the the app on the App Store is the same.
