### ISSUE TITLE
Censorship resistance of the Android and iOS applications

### ISSUE THREAD

**Issue by shalzz** [argentlabs/argent-contracts#279]
## Issue description
How censorship resistant are the argent android and iOS applications?
In terms of what RPC endpoints do they rely on, if any and if any critical functionality can be disabled by taking out specific endpoint or disabling/blocking a DNS domain, etc

These are questions that I think the argent teams needs to consider and address especially since the applications are not yet open sourced and available outside the play store yet, in situations where governments and states where there are not favourable regulations for cryptocurrencies and argent manages to gain a fair market share in those markets only for the government to then decide to ban this specific applications for socio-political reasons.

**Comment by juniset** [comment]
This is the repository of the smart-contracts for the Argent Vaults. Please contact us on Discord to discuss topics not related to contracts.
