### ISSUE TITLE
Request: Improve user experience for Guardian when approving transaction

### ISSUE THREAD

**Issue by avalyn2** [argentlabs/argent-contracts#291]
This message is all but user-friendly. Can the JSON be presented in a different format?

![image](https://user-images.githubusercontent.com/32930476/154799366-89e497a2-b56d-40f9-8505-c85ba3fb90ad.png)

**Comment by juniset** [comment]
This is the repository of the smart-contracts. Please contact support@argent.xyz for feedback or issues on the mobile application.
