### ISSUE TITLE
Declare the contract in the Cairo 1 wallet

### ISSUE THREAD

**Issue by p4vluk** [argentlabs/argent-contracts#329]
## Issue description

pl: Execution was reverted; failure reason: [0x617267656e742f696e76616c69642d74782d76657273696f6e].

Built the contract in Cairo 0, but after upgrading the Argent X wallet to Cairo 1, declaring the contract resulted in an error.

pl: Execution was reverted; failure reason: [0x617267656e742f696e76616c69642d74782d76657273696f6e].

PS: decoded hex(0x617267656e742f696e76616c69642d74782d76657273696f6e) -> str "?argent/invalid-tx-version"

**Comment by sgc-code** [comment]
you probably meant to write to this other repo, these are the ethereum L1 contracts
https://github.com/argentlabs/argent-contracts-starknet
