### ISSUE TITLE
Repeated warnings during tests: "WARNING: Multiple definitions for isRegisteredModule"

### ISSUE THREAD

**Issue by Jaimeloeuf** [argentlabs/argent-contracts#38]
There were many warnings emitted during the tests, most of which are the same warning,
***"WARNING: Multiple definitions for isRegisteredModule***

Would just like to know if this is an expected behavior or not, and if so, I would love to understand why this is emitted or where is it from, as I am unable to find any resources of this online.
After skimming through the tests slightly, suspect might be caused by modules being reloaded/re-deployed everytime in beforeEach hooks.

**Comment by olivdb** [comment]
This warning is expected and is thrown by `ethers.js` (a dependency of `etherlime`) when deploying a contract having two functions with the same name (in this case `isRegisteredModule(address[])` and `isRegisteredModule(address)`). See ethers-io/ethers.js#499.

**Comment by Jaimeloeuf** [comment]
@olivdb I see, thanks alot for the swift response and appreciate the help!
