### ISSUE TITLE
TransferManager out of gas

### ISSUE THREAD

**Issue by leonprou** [argentlabs/argent-contracts#40]
Hey guys,

I try to deploy `TransferManager` but I'm getting out of gas error.
First I ran all the 6 basic scripts, and then I try to upgrade to new versions. Some of the upgrades are failing, I'm most interested in `10_upgrade_v1_4` because of the new TransferManager.
I get out of gas both on Kovan and ganache, so I think there's some error there. I noticed that you removed the old `TokenTransfer` module not so long ago, so maybe it's related.
txhash: https://kovan.etherscan.io/tx/0xba1ad6197c037a83333ea5e6ec9f6f420831c0d13d97df00a70821a6f44c43f2

**Comment by olivdb** [comment]
Hi @leonprou,

Are you using `deploy.sh` for your deployment? 
```
./deploy.sh ganache 1 2 3 4 5 6 7 8 9 10
```
If not, make sure you are specifying a large enough number of runs for the compiler (200 should be sufficient)
```
etherlime compile --runs=200
etherlime deploy --file deployment/1_setup_test_environment.js --network ganache --compile false
etherlime deploy --file deployment/2_deploy_contracts.js --network ganache --compile false
...
etherlime deploy --file deployment/10_upgrade_v1_4.js --network ganache --compile false
```

**Comment by leonprou** [comment]
@olivdb no, where to find `deploy.sh` file? It's part of the repo?

**Comment by olivdb** [comment]
Ah sorry, it's indeed not currently part of the repo. So to deploy locally you'll need to run each deployment file in order:
```
etherlime compile --runs=200
etherlime deploy --file deployment/1_setup_test_environment.js --network ganache --compile false
etherlime deploy --file deployment/2_deploy_contracts.js --network ganache --compile false
etherlime deploy --file deployment/3_setup_contracts.js --network ganache --compile false
etherlime deploy --file deployment/4_finalise_test_environment.js --network ganache --compile false
etherlime deploy --file deployment/5_deploy_modules_v1.js --network ganache --compile false
etherlime deploy --file deployment/6_register_modules_v1.js --network ganache --compile false
etherlime deploy --file deployment/7_upgrade_v1_1.js --network ganache --compile false
etherlime deploy --file deployment/8_upgrade_v1_2.js --network ganache --compile false
etherlime deploy --file deployment/9_upgrade_v1_3.js --network ganache --compile false
etherlime deploy --file deployment/10_upgrade_v1_4.js --network ganache --compile false
```

**Comment by leonprou** [comment]
@olivdb thanks! adding `--runs=200` solved this. Didn't worked with `etherlime` before

**Comment by leonprou** [comment]
@olivdb Found another small issue FYI. Calling `createWallet` script failed for me with `TransferManager` deployed by `deployment/10_upgrade_v1_4.js` Looking into the `deployment/10_upgrade_v1_4.js` I've found that `oldLimitManager` should be zero address (and not  `TokenTransfer`), I think it's because you don't deploy and register the old `TokenTransfer` module anymore.

**Comment by olivdb** [comment]
Good catch, I fixed that, thanks!
